# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: 🐳🧪 Test Docker Image

on:
  workflow_call:
    inputs:
      artifact_name:
        required: true
        description: The name of the artifact containing the Docker image
        type: string
      image_name:
        required: true
        description: The local name of the Docker image
        type: string

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Download Docker image artifact
        uses: actions/download-artifact@v8
        with:
          name: ${{ inputs.artifact_name }}
          path: /tmp

      - name: 🐳 Load Docker image
        run: |
          docker load --input /tmp/${{ inputs.image_name }}.tar
          docker image ls -a

      - name: 🐳🧪 Test Docker image
        run: |
          docker run --rm --detach --name test_container ${{ inputs.image_name }}:latest
          for i in {1..10}; do
            status=$(docker inspect --format='{{.State.Health.Status}}' test_container)
            health_details=$(docker inspect --format='{{json .State.Health}}' test_container)
            echo "Health status: $status"
            echo "Health details: $health_details"
            if [ "$status" = "healthy" ]; then break; fi
            sleep 6
          done
          if [ "$status" != "healthy" ]; then
            echo "Container did not become healthy after 10 attempts."
            docker logs test_container
            exit 1
          fi
          docker stop test_container
