# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Release Please Automerge

on:
  pull_request_target:
    types:
      - opened
      - synchronized
      - labeled

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: "${{ contains(github.event.pull_request.labels.*.name, 'autorelease: pending') }}"
    steps:
      - name: Automerge Release PR
        env:
          GH_TOKEN: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
        run: |
          gh pr merge "$PR_URL" --auto --merge
